### ISSUE TITLE
Firefox starts but isn’t executing any tests

### ISSUE THREAD

**Issue by mischah** [dalekjs/dalek-browser-firefox#13]
I’m calling my test file with:

```
dalek tests/firstTests.js -b firefox
```

Firefox (v30) starts but before executing any test the terminal is throwing the following error:

```
$ dalek tests/firstTests.js -b firefox
Running tests
Running Browser: Mozilla Firefox
>> ERROR: Error: socket hang up

net.js:1236
    throw new Error('Not running');
          ^
Error: Not running
    at Server.close (net.js:1236:11)
    at WebDriverServer.kill (/Users/mkuehnel/Documents/Projects/dalekjs-hackathon/node_modules/dalek-browser-firefox/lib/webdriver.js:98:17)
    at Object.FirefoxDriver.kill (/Users/mkuehnel/Documents/Projects/dalekjs-hackathon/node_modules/dalek-browser-firefox/index.js:434:28)
    at EventEmitter.emit (/Users/mkuehnel/Documents/Projects/dalekjs-hackathon/node_modules/dalekjs/node_modules/eventemitter2/lib/eventemitter2.js:312:17)
    at Object.Dalek._shutdown (/Users/mkuehnel/Documents/Projects/dalekjs-hackathon/node_modules/dalekjs/lib/dalek.js:333:24)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
```

**Comment by beardedbrew** [comment]
Any update? Currently running Firefox 29 and it's super buggy.

**Comment by webmailcontatos** [comment]
Any update?

**Comment by stayen** [comment]
Any update? Latest versions Firefox can't be used at all, due to this behaviour.

NB: DalekJS looks abandoned, is it?

**Comment by mischah** [comment]
@stayen 

Dalek.js is dead 😢 

See https://twitter.com/dalekjs/status/734653713554493440

**Comment by stayen** [comment]
@mischah Alas, seems true, I switched to another testing package.

Pity, trying and studying Dalek.js was fun.
